// Course content for IAFF / PSC 1001 — classical realism + game theory + analysis.
export const COURSE = {
  code: "IAFF / PSC 1001",
  title: "Introduction to International Relations",
  subtitle: "Classical Realism, Strategy & Analysis",
  credits: 3,
};

// readingLinks is parallel to readings: same order, same length.
// Each entry is one of:
//   { title, url, source }             ⇒ direct link button (e.g. JSTOR, Internet Archive)
//   { title, search: true, query }     ⇒ no public link; UI renders Google / Amazon / Library buttons
//   null                               ⇒ legacy fallback (UI builds a Google search from the reading text)
//
// Textbook used throughout: Goldstein & Pevehouse, "International Relations" (Pearson),
// a widely adopted intro textbook. No free public full-text exists, so textbook chapters
// use search buttons; supplementary readings link directly when an open copy is available.
export const WEEKS = [
  { n: 1, unit: "I · Foundations & the Analyst's Toolkit", title: "What Is IR? Levels of Analysis",
    blurb: "International relations is the study of power, war, cooperation, and order among states and other actors. We begin with the analyst's first move: deciding the level of analysis — individual, state, or system — at which to explain an event.",
    objectives: ["Distinguish the three levels of analysis", "Tell explanation apart from description", "Frame a researchable question"],
    terms: ["anarchy", "levels of analysis", "system / state / individual", "variable", "explanation vs. description"],
    readings: [
      "Goldstein & Pevehouse, International Relations — Ch. 1: The Globalization of International Relations",
      "J.D. Singer, “The Level-of-Analysis Problem in International Relations” (World Politics, 1961)",
    ],
    readingLinks: [
      { title: "Goldstein & Pevehouse, International Relations — Ch. 1", search: true, query: '"International Relations" Goldstein Pevehouse "Chapter 1" globalization' },
      { title: "Singer, “The Level-of-Analysis Problem in IR”", url: "https://www.jstor.org/stable/2009557", source: "JSTOR" },
    ],
    keyTerms: {
      "individual": "Explaining world events by looking at specific people — leaders, their psychology, beliefs, and choices. For example, blaming a war on one ruler's ambition.",
      "state": "Explaining events by looking inside countries — their type of government, economy, and domestic politics.",
      "system": "Explaining events by looking at the structure of the whole international system, like how power is spread among states, rather than at any one country.",
      "agent-structure": "The debate over whether actors (agents) shape the world through their choices, or whether the larger structure they live in shapes what they can do. Most scholars say it's both.",
      "parsimony": "A preference for simple theories that explain a lot using few moving parts. A parsimonious theory is lean — it doesn't pile on extra factors.",
      "falsifiability": "A theory counts as scientific only if some possible evidence could prove it wrong. If nothing could ever disprove it, it isn't a real explanation.",
      "explanation vs. description": "Description tells you what happened; explanation tells you why it happened. Good analysis aims for the why.",
    },
    questions: ["Is the system or the statesman the better unit of analysis?", "What evidence would change your mind about a theory?"] },
  { n: 2, unit: "I · Foundations & the Analyst's Toolkit", title: "Anarchy, the State & the Balance of Power",
    blurb: "The modern system rests on sovereign states under anarchy — no authority above them. Realism's organizing principle, the balance of power, explains how states check one another to survive.",
    objectives: ["Explain anarchy and sovereignty", "Describe balance-of-power logic", "Trace the system from Westphalia to today"],
    terms: ["sovereignty", "Westphalia", "balance of power", "great power", "polarity"],
    readings: [
      "Goldstein & Pevehouse, International Relations — Ch. 2: Realist Theories",
      "Stephen M. Walt, The Origins of Alliances — Ch. 1: Introduction & the Balance of Threat",
    ],
    readingLinks: [
      { title: "Goldstein & Pevehouse, International Relations — Ch. 2", search: true, query: '"International Relations" Goldstein Pevehouse "Chapter 2" realist theories' },
      { title: "Walt, The Origins of Alliances", url: "https://archive.org/details/originsofallianc0000walt", source: "Internet Archive" },
    ],
    keyTerms: {
      "anarchy": "In IR, anarchy doesn't mean chaos — it means there is no world government above states to enforce rules or protect them. Each state is on its own.",
      "sovereignty": "The principle that each state has supreme authority within its own borders and answers to no higher power.",
      "balance of power": "When states form alliances and build forces to stop any single state from becoming strong enough to dominate everyone else.",
      "bipolarity": "An international system with two dominant great powers, like the United States and the USSR during the Cold War.",
      "multipolarity": "An international system with three or more great powers competing.",
      "self-help": "Because no one else will guarantee their safety under anarchy, states must rely on themselves to survive.",
      "polarity": "The number of great-power “poles” in the system: one is unipolar, two is bipolar, several is multipolar.",
    },
    questions: ["Does anarchy force similar behavior on all states?", "Is bipolarity or multipolarity more stable?"] },
  { n: 3, unit: "II · The Classical Realist Tradition", title: "Thucydides: The Birth of Realism",
    blurb: "Twenty-four centuries ago Thucydides explained the Peloponnesian War through fear, honor, and interest. The Melian Dialogue — “the strong do what they can and the weak suffer what they must” — is realism's founding text.",
    objectives: ["Extract realist logic from Thucydides", "Analyze the Melian Dialogue as strategic interaction", "Assess power and necessity in war"],
    terms: ["fear · honor · interest", "the Melian Dialogue", "hegemony", "necessity", "proto security dilemma"],
    readings: [
      "Thucydides, History of the Peloponnesian War — Melian Dialogue (Book V, excerpt)",
      "Thucydides, History of the Peloponnesian War — Pericles' Funeral Oration (Book II, excerpt)",
    ],
    readingLinks: [
      { title: "Thucydides, Melian Dialogue (History, Book 5)", url: "https://classics.mit.edu/Thucydides/pelopwar.5.fifth.html", source: "MIT Classics" },
      { title: "Thucydides, Pericles' Funeral Oration (History, Book 2)", url: "https://classics.mit.edu/Thucydides/pelopwar.2.second.html", source: "MIT Classics" },
    ],
    keyTerms: {
      "fear, honor, interest": "Thucydides' three timeless motives that drive states to act — and especially to go to war.",
      "Melian Dialogue": "A famous exchange in which powerful Athens tells tiny Melos that “the strong do what they can and the weak suffer what they must.” A classic statement of realism.",
      "hegemony": "Leadership or dominance of one state over others in a region or across the whole system.",
      "necessity": "The realist idea that states are sometimes forced into harsh actions by their circumstances rather than by free choice.",
      "security dilemma (proto)": "When one state's steps to feel safer make others feel less safe, prompting them to respond — so everyone ends up more threatened. Thucydides hints at this early.",
      "power": "The ability to get others to do what you want, or to resist their pressure — central to how realists explain politics.",
    },
    questions: ["Were the Athenians acting rationally?", "Did Melos have any credible option?"] },
  { n: 4, unit: "II · The Classical Realist Tradition", title: "Machiavelli: Statecraft, Virtù & Necessity",
    blurb: "Machiavelli separates political success from conventional morality. The prince must master virtù (skill, will) against fortuna (chance), and learn “not to be good” when necessity demands — the logic of raison d'état.",
    objectives: ["Define virtù and fortuna", "Explain raison d'état", "Evaluate the split between politics and ordinary morality"],
    terms: ["virtù", "fortuna", "raison d'état", "the lion and the fox", "necessità"],
    readings: [
      "Niccolò Machiavelli, The Prince — Chs. 15, 17, 18",
      "Niccolò Machiavelli, Discourses on Livy (excerpt)",
    ],
    readingLinks: [
      { title: "Machiavelli, The Prince", url: "https://www.gutenberg.org/files/1232/1232-h/1232-h.htm", source: "Project Gutenberg" },
      { title: "Machiavelli, Discourses on Livy", url: "https://www.gutenberg.org/files/10827/10827-h/10827-h.htm", source: "Project Gutenberg" },
    ],
    keyTerms: {
      "virtù": "A leader's skill, boldness, and force of will — the ability to seize opportunities and master events.",
      "fortuna": "“Fortune” or luck — the unpredictable forces and chance events a leader cannot control but must respond to.",
      "raison d'état": "“Reason of state” — the idea that protecting the state can justify actions ordinary morality would condemn.",
      "necessity": "When circumstances leave a leader no real choice but to act, even ruthlessly, to preserve the state.",
      "dirty hands": "The dilemma that political leaders sometimes must do morally troubling things for the greater good of those they protect.",
    },
    questions: ["Is “dirty hands” justified for leaders?", "Is Machiavelli amoral, or a realist about morality?"] },
  { n: 5, unit: "II · The Classical Realist Tradition", title: "Hobbes: Anarchy & the State of Nature",
    blurb: "Hobbes's “war of all against all” is the classic model of international anarchy. Without a common sovereign, life is insecure and self-help rules — the philosophical root of the security dilemma.",
    objectives: ["Connect Leviathan to the international system", "Explain the roots of the security dilemma", "Assess the war of all against all"],
    terms: ["state of nature", "war of all against all", "Leviathan / sovereign", "self-help", "security dilemma"],
    readings: [
      "Thomas Hobbes, Leviathan — Ch. 13: Of the Natural Condition of Mankind",
    ],
    readingLinks: [
      { title: "Hobbes, Leviathan (ch. 13: Of the Natural Condition of Mankind)", url: "https://www.gutenberg.org/files/3207/3207-h/3207-h.htm", source: "Project Gutenberg" },
    ],
    keyTerms: {
      "state of nature": "A thought experiment imagining life with no government — for Hobbes, dangerous and insecure. IR theorists compare it to the anarchic world of states.",
      "Leviathan": "Hobbes's name for the all-powerful sovereign or government that ends the chaos of the state of nature by enforcing order.",
      "war of all against all": "Hobbes's phrase for life without a common authority, where everyone fears everyone and no one is safe.",
      "sovereign": "The supreme authority — a person or body — whose power keeps peace within a state. There is no such sovereign over the whole world.",
      "self-help": "With no global sovereign, each state must provide for its own security.",
      "security dilemma": "When a state's steps to protect itself make rivals feel threatened, prompting them to arm too, leaving everyone less secure.",
    },
    questions: ["Are states really like Hobbesian individuals?", "Why is there no global Leviathan?"] },
  { n: 6, unit: "II · The Classical Realist Tradition", title: "Carr, Morgenthau & Niebuhr",
    blurb: "Twentieth-century realism matures. Carr attacks utopian thinking; Morgenthau gives realism its six principles centered on the national interest defined as power; Niebuhr and Chris Brown press the question of realist ethics.",
    objectives: ["State Morgenthau's six principles", "Explain Carr's utopia-vs-reality critique", "Weigh realism's moral claims"],
    terms: ["national interest", "six principles of realism", "utopianism vs. realism", "prudence", "realist ethics"],
    readings: [
      "E.H. Carr, The Twenty Years' Crisis, 1919–1939 (excerpt)",
      "Hans J. Morgenthau, Politics Among Nations — Ch. 1: Six Principles of Political Realism",
      "Reinhold Niebuhr, Moral Man and Immoral Society (excerpt on power and politics)",
    ],
    readingLinks: [
      { title: "Carr, The Twenty Years' Crisis", url: "https://archive.org/details/twentyyearscrisi0000carr", source: "Internet Archive" },
      { title: "Morgenthau, Politics Among Nations", url: "https://archive.org/details/politicsamongnat00morg", source: "Internet Archive" },
      { title: "Niebuhr, Moral Man and Immoral Society", url: "https://archive.org/details/moralmanimmorals0000nieb", source: "Internet Archive" },
    ],
    keyTerms: {
      "utopianism": "The idealist belief — which Carr criticized — that reason, law, and good intentions can overcome power politics. Carr called it naive.",
      "national interest": "What a state needs to protect and advance; for realists, defined mainly in terms of power and security.",
      "six principles": "Morgenthau's six foundational rules of realism, built around the idea that politics is governed by interest defined as power.",
      "realist ethics": "The realist view that leaders should be judged by the consequences of their actions for the state, not by abstract moral rules.",
      "power": "For Morgenthau, the central currency of politics — the national interest is “interest defined as power.”",
      "prudence": "The practical wisdom to weigh consequences and act with restraint — for realists, the highest political virtue.",
    },
    questions: ["Is “interest defined as power” a useful guide?", "Can realism be ethical?"] },
  { n: 7, unit: "III · Game Theory & Methods of Analysis", title: "Game Theory I: Strategic Interaction  ·  Midterm",
    blurb: "Game theory models choices that depend on what others do. We define rationality and payoffs, build a 2×2 matrix, and find the Nash equilibrium — the point where no player wants to switch unilaterally.",
    objectives: ["Define rational choice and payoffs", "Build a 2×2 payoff matrix", "Find a Nash equilibrium"],
    terms: ["rationality", "payoffs / preferences", "strategy", "Nash equilibrium", "dominant strategy"],
    readings: [
      "James D. Morrow, Game Theory for Political Scientists — Ch. 1: Overview of Game Theory",
      "Frieden, Lake & Schultz, World Politics: Interests, Interactions, Institutions — Ch. 2: Understanding Interests, Interactions, and Institutions",
    ],
    readingLinks: [
      { title: "Morrow, Game Theory for Political Scientists", search: true, query: '"Game Theory for Political Scientists" Morrow chapter 1' },
      { title: "Frieden, Lake & Schultz, World Politics", search: true, query: '"World Politics" "Interests Interactions Institutions" Frieden Lake Schultz chapter 2' },
    ],
    keyTerms: {
      "rationality": "In game theory, acting to get the outcome you most prefer, given what you expect others to do. It doesn't mean “smart” — just goal-directed.",
      "payoff": "The value a player gets from an outcome; higher payoffs are more preferred. Shown as numbers in a game matrix.",
      "Nash equilibrium": "A stable outcome where no player can do better by changing their move alone, given what everyone else is doing.",
      "Prisoner's Dilemma": "A famous game where both players, acting rationally, betray each other — even though both would be better off cooperating.",
      "dominant strategy": "A move that gives you the best result no matter what the other player does.",
      "strategy": "A complete plan of action for a player in a game.",
    },
    questions: ["When does “rational” behavior produce a bad outcome?", "What does an equilibrium actually mean?"],
    games: [{
      name: "Prisoner's Dilemma", rows: "You", cols: "The other state", options: ["Cooperate", "Defect"],
      payoffs: [[[3,3],[0,5]],[[5,0],[1,1]]], nash: ["1-1"],
      note: "Both players have a dominant strategy to defect, so the only Nash equilibrium is (Defect, Defect) = 1,1 — even though both would be better off at (Cooperate, Cooperate) = 3,3. This is the engine behind arms races and the security dilemma.",
    }] },
  { n: 8, unit: "III · Game Theory & Methods of Analysis", title: "Game Theory II: The Core Games",
    blurb: "The Prisoner's Dilemma, Stag Hunt, and Chicken capture the deep structure of IR. We formalize the security dilemma and show how repetition — the shadow of the future — and tit-for-tat can rescue cooperation under anarchy.",
    objectives: ["Distinguish PD, Stag Hunt, and Chicken", "Explain why anarchy need not mean permanent conflict", "Apply tit-for-tat"],
    terms: ["Prisoner's Dilemma", "Stag Hunt", "Chicken", "shadow of the future", "tit-for-tat"],
    readings: [
      "Robert Axelrod, The Evolution of Cooperation (excerpt on the iterated Prisoner's Dilemma)",
      "Robert Jervis, “Cooperation Under the Security Dilemma” (World Politics, 1978)",
    ],
    readingLinks: [
      { title: "Axelrod, The Evolution of Cooperation", url: "https://archive.org/details/evolutionofcoope00axel", source: "Internet Archive" },
      { title: "Jervis, “Cooperation Under the Security Dilemma”", url: "https://www.jstor.org/stable/2009958", source: "JSTOR" },
    ],
    keyTerms: {
      "tit-for-tat": "A simple, successful strategy: cooperate first, then do whatever your opponent did last time. It rewards cooperation and punishes betrayal.",
      "repeated game": "A game played over and over by the same players, which can make cooperation possible because today's choices affect future rounds.",
      "shadow of the future": "The idea that when players expect to interact again, the value of future rounds makes them more willing to cooperate now.",
      "conditional cooperation": "Cooperating only as long as the other side does too, and withdrawing cooperation if they betray you.",
      "Stag Hunt": "A game where both players gain most by cooperating (hunting a stag together) but are tempted by the safer, smaller solo payoff (a hare). It models trust.",
    },
    questions: ["Was the Cold War a Prisoner's Dilemma or a game of Chicken?", "Can repetition really rescue cooperation?"],
    games: [
      { name: "Prisoner's Dilemma", rows: "You", cols: "Them", options: ["Cooperate", "Defect"],
        payoffs: [[[3,3],[0,5]],[[5,0],[1,1]]], nash: ["1-1"],
        note: "One equilibrium: mutual defection (1,1). Conflict is the trap even though both prefer (3,3)." },
      { name: "Stag Hunt", rows: "You", cols: "Them", options: ["Hunt Stag", "Hunt Hare"],
        payoffs: [[[4,4],[1,3]],[[3,1],[3,3]]], nash: ["0-0","1-1"],
        note: "Two equilibria: the great (Stag, Stag) = 4,4 and the safe (Hare, Hare) = 3,3. Cooperation is possible — it just needs trust. This models alliances and collective security." },
      { name: "Chicken", rows: "You", cols: "Them", options: ["Swerve", "Stay straight"],
        payoffs: [[[3,3],[2,4]],[[4,2],[0,0]]], nash: ["0-1","1-0"],
        note: "Two equilibria, both where one side backs down. Mutual nerve = catastrophe (0,0). Whoever credibly commits to staying straight wins — the logic of brinkmanship and nuclear crises." },
    ] },
  { n: 9, unit: "III · Game Theory & Methods of Analysis", title: "Game Theory III: Bargaining & Deterrence  ·  Problem set",
    blurb: "If war is costly, why does it happen? Fearon's bargaining model points to private information and commitment problems. Schelling shows how credible threats, signaling, and brinkmanship make deterrence work — or fail.",
    objectives: ["Explain why rational states still fight", "Analyze what makes a threat credible", "Model deterrence and coercion"],
    terms: ["bargaining model of war", "private information", "commitment problem", "credibility", "brinkmanship"],
    readings: [
      "James D. Fearon, “Rationalist Explanations for War” (International Organization, 1995)",
      "Thomas C. Schelling, Arms and Influence (excerpts on signaling and brinkmanship)",
    ],
    readingLinks: [
      { title: "Fearon, “Rationalist Explanations for War”", url: "https://web.stanford.edu/group/fearon-research/cgi-bin/wordpress/wp-content/uploads/2013/10/Rationalist-Explanations-for-War.pdf", source: "Stanford" },
      { title: "Schelling, Arms and Influence", url: "https://archive.org/details/armsinfluence0000sche", source: "Internet Archive" },
    ],
    keyTerms: {
      "credibility": "Whether others actually believe you'll follow through on a threat or promise. A threat only works if it's believable.",
      "commitment": "Locking yourself into a course of action so others know you can't back down, which can make your threats more credible.",
      "brinkmanship": "Deliberately pushing a dangerous situation to the edge of disaster to force the other side to back down.",
      "MAD": "Mutual Assured Destruction — the Cold War logic that if both sides can destroy each other, neither will dare strike first.",
      "Chicken": "A game where two players race toward a head-on crash; whoever swerves loses, but if neither swerves both are destroyed. It models nuclear crises.",
      "bargaining model of war": "The idea that war is a costly failure of bargaining, often caused by private information or commitment problems.",
    },
    questions: ["If war is costly, why does it happen at all?", "What makes a threat believable?"],
    games: [{
      name: "Deterrence (a game of Chicken)", rows: "You", cols: "Adversary", options: ["Back down", "Hold firm"],
      payoffs: [[[3,3],[2,4]],[[4,2],[0,0]]], nash: ["0-1","1-0"],
      note: "Deterrence works by making your threat to 'hold firm' more credible than the adversary's — so they back down. But if both hold firm, you reach the catastrophe cell (0,0). Credibility, signaling, and commitment are everything." },
    ] },
  { n: 10, unit: "III · Game Theory & Methods of Analysis", title: "Methods of Analysis  ·  Policy memo due",
    blurb: "How do we move from theory to disciplined judgment? We cover the case-study and comparative methods, counterfactual reasoning, process tracing, and Analysis of Competing Hypotheses — the structured techniques used in scholarship and intelligence.",
    objectives: ["Design a disciplined case study", "Use counterfactual reasoning", "Apply Analysis of Competing Hypotheses (ACH)"],
    terms: ["case-study method", "comparative method", "counterfactual", "process tracing", "ACH"],
    readings: [
      "Alexander L. George & Andrew Bennett, Case Studies and Theory Development in the Social Sciences — Ch. 1: Case Studies and Theory Development",
      "Richards J. Heuer, Psychology of Intelligence Analysis — Ch. 8: Analysis of Competing Hypotheses",
    ],
    readingLinks: [
      { title: "George & Bennett, Case Studies and Theory Development", search: true, query: '"Case Studies and Theory Development in the Social Sciences" George Bennett chapter 1' },
      { title: "Heuer, Psychology of Intelligence Analysis", url: "https://www.cia.gov/static/9a5f1162fd0932c29bfed1c030edf4ae/Pyschology-of-Intelligence-Analysis.pdf", source: "CIA.gov" },
    ],
    keyTerms: {
      "case study": "An in-depth study of a single event or example to understand how and why something happened.",
      "process tracing": "Carefully following the chain of steps inside a case to see what actually caused the outcome, like a detective.",
      "counterfactual": "Asking “what would have happened if...?” to test whether a cause really mattered.",
      "congruence": "Checking whether a theory's predictions match what we actually observe in a case.",
      "mechanism": "The specific cause-and-effect process that links a cause to its outcome — the “gears” that make something happen.",
      "ACH": "Analysis of Competing Hypotheses — a structured method that lists rival explanations and tests the evidence against all of them to reduce bias.",
    },
    questions: ["How do you guard analysis against bias?", "What makes a counterfactual disciplined rather than lazy?"] },
  { n: 11, unit: "IV · Newer Theories as Challengers", title: "Neorealism & the Structural Turn",
    blurb: "Waltz relocates realism's engine from human nature to the structure of the system. Offensive realists (Mearsheimer) and defensive realists (Jervis) then disagree about how much power a state should seek.",
    objectives: ["Contrast classical and neorealism", "Explain offensive vs. defensive realism", "Assess the structural explanation"],
    terms: ["structure", "neorealism", "offensive vs. defensive realism", "relative gains", "polarity"],
    readings: [
      "Kenneth N. Waltz, Theory of International Politics — Ch. 5: Political Structures & Ch. 6: Anarchic Orders and Balances of Power",
      "John J. Mearsheimer, The Tragedy of Great Power Politics — Ch. 2: Anarchy and the Struggle for Power",
    ],
    readingLinks: [
      { title: "Waltz, Theory of International Politics", url: "https://archive.org/details/theoryofinternat0000walt", source: "Internet Archive" },
      { title: "Mearsheimer, The Tragedy of Great Power Politics", url: "https://archive.org/details/tragedyofgreatpo0000mear", source: "Internet Archive" },
    ],
    keyTerms: {
      "structure": "The overall shape of the international system — especially how power is distributed — which shapes how states behave regardless of their internal politics.",
      "polarity": "The number of great powers in the system, which neorealists say strongly affects stability.",
      "offensive realism": "Mearsheimer's view that states seek to maximize power and dominance because that is the safest path in an uncertain world.",
      "defensive realism": "The Waltz/Jervis view that states seek just enough security, and that grabbing too much power can backfire.",
      "distribution of capabilities": "How military and economic power is spread among states — the key feature of structure for neorealists.",
      "relative gains": "Caring not just about your own benefit, but whether you gain more or less than rivals — which matters when survival is at stake.",
    },
    questions: ["Does structure or human nature drive conflict?", "Is more power always safer?"] },
  { n: 12, unit: "IV · Newer Theories as Challengers", title: "Institutions & Ideas  ·  Crisis simulation",
    blurb: "Two challengers to realism, in brief: liberal institutionalism (Keohane) argues institutions let states pursue absolute gains; constructivism (Wendt) argues that “anarchy is what states make of it.” Then we test the toolkit under pressure in a crisis simulation.",
    objectives: ["Summarize the institutionalist and constructivist challenges", "Weigh them against realism", "Perform analysis under simulation pressure"],
    terms: ["liberal institutionalism", "absolute gains", "constructivism", "norms / identity", "social construction"],
    readings: [
      "Robert O. Keohane, After Hegemony: Cooperation and Discord in the World Political Economy — Ch. 6: A Functional Theory of International Regimes",
      "Alexander Wendt, “Anarchy Is What States Make of It: The Social Construction of Power Politics” (International Organization, 1992)",
    ],
    readingLinks: [
      { title: "Keohane, After Hegemony", url: "https://archive.org/details/afterhegemony00robe", source: "Internet Archive" },
      { title: "Wendt, “Anarchy Is What States Make of It”", url: "https://www.jstor.org/stable/2706858", source: "JSTOR" },
    ],
    keyTerms: {
      "absolute gains": "Caring about how much you gain overall, regardless of how others do — the focus of liberal institutionalists.",
      "relative gains": "Caring about whether you gain more than rivals — the classic realist concern.",
      "regime": "A set of rules, norms, and institutions that govern state behavior in one area, such as trade or arms control.",
      "norm": "A shared expectation about proper behavior that shapes what states see as appropriate.",
      "identity": "How a state sees itself and others, which constructivists say shapes its interests and actions.",
      "social construction": "The constructivist idea that key features of world politics (like anarchy or enmity) are created by shared ideas and beliefs, not fixed by nature. “Anarchy is what states make of it.”",
    },
    questions: ["Do institutions change behavior or just reflect power?", "Are state interests fixed, or socially constructed?"] },
  { n: 13, unit: "V · Application, Practice & Synthesis", title: "Applying the Toolkit: Great-Power Competition",
    blurb: "We turn the full kit — classical realism plus game theory plus method — on contemporary great-power rivalry: deterrence, alliance dilemmas, and the spiral vs. deterrence models of escalation.",
    objectives: ["Analyze a current rivalry with realism and game theory", "Evaluate alliance and deterrence dynamics", "Integrate theory and method"],
    terms: ["great-power competition", "deterrence", "entrapment / abandonment", "spiral vs. deterrence model", "escalation"],
    readings: [
      "John J. Mearsheimer & Stephen M. Walt, “The Case for Offshore Balancing” (Foreign Affairs, July/Aug. 2016)",
      "Review: Robert Jervis, “Cooperation Under the Security Dilemma” (JSTOR) + Schelling, Arms and Influence (key passages)",
    ],
    readingLinks: [
      { title: "Mearsheimer & Walt, “The Case for Offshore Balancing”", url: "https://www.mearsheimer.com/wp-content/uploads/2019/06/Case-for-Offshore-Balancing.pdf", source: "Mearsheimer.com" },
      { title: "Jervis, “Cooperation Under the Security Dilemma” (review)", url: "https://www.jstor.org/stable/2009958", source: "JSTOR" },
    ],
    keyTerms: {
      "rivalry": "A long-running competitive and often hostile relationship between two states.",
      "alliance dilemma": "The tension allies face between fear of being dragged into a partner's war (entrapment) and fear of being deserted (abandonment).",
      "spiral model": "The idea that hostile actions taken for defense are misread as aggression, triggering a cycle of escalating fear and conflict.",
      "escalation": "The process by which a conflict grows more intense or dangerous, step by step.",
      "signaling": "Sending costly or credible signs of your intentions or resolve so others read you correctly.",
      "deterrence model": "The view that conflict comes from too little firmness, so showing strength and resolve prevents aggression — the opposite warning from the spiral model.",
    },
    questions: ["Is today's rivalry a security dilemma or genuine aggression?", "What does game theory predict here?"] },
  { n: 14, unit: "V · Application, Practice & Synthesis", title: "Statecraft, Practice & Synthesis  ·  Final",
    blurb: "Foreign policy is made at home and abroad at once. Putnam's two-level games show leaders bargaining with adversaries and their own publics simultaneously. We integrate the term and ask which lens explained the most.",
    objectives: ["Explain two-level games", "Connect theory to the policy process", "Synthesize the course"],
    terms: ["statecraft", "diplomacy", "two-level games", "prudence", "the policy process"],
    readings: [
      "Robert D. Putnam, “Diplomacy and Domestic Politics: The Logic of Two-Level Games” (International Organization, 1988)",
    ],
    readingLinks: [
      { title: "Putnam, “Diplomacy and Domestic Politics: The Logic of Two-Level Games”", url: "https://www.jstor.org/stable/2706785", source: "JSTOR" },
    ],
    keyTerms: {
      "win-set": "The range of deals a leader can get accepted at home. Bigger win-sets make international agreement easier.",
      "ratification": "The step where a deal must be approved domestically — by a legislature or public — before it becomes binding.",
      "audience cost": "The political price a leader pays at home for backing down after making a public threat or promise, which can make their commitments credible.",
      "side payment": "An extra incentive added to a deal to win over a reluctant party at home or abroad.",
      "synergistic linkage": "Connecting issues so a move in one area changes what's possible in another, helping a leader build support for a deal.",
      "two-level game": "Putnam's idea that leaders bargain on two boards at once — with foreign counterparts and with their own domestic public.",
    },
    questions: ["How does domestic politics constrain foreign policy?", "Which lens explained the most this term?"] },
];

export const HOME = {
  n: 0, unit: "Course Home", title: "Course Overview",
  blurb: "An introduction to international relations built on the classical realist tradition, the formal tools of game theory, and rigorous methods of analysis. Pick a week from the left to study it, then open the Tutor tab to be quizzed Socratically — with a direct answer the moment you want one.",
  objectives: ["Explain classical realism from Thucydides to Morgenthau", "Model interactions with game theory", "Apply disciplined methods of analysis"],
  terms: ["classical realism", "game theory", "methods of analysis", "policy & practice"],
  readings: ["Course textbook: Goldstein & Pevehouse, International Relations (Pearson) — see each week for the assigned chapter"],
  readingLinks: [
    { title: "Goldstein & Pevehouse, International Relations (Pearson)", search: true, query: '"International Relations" Goldstein Pevehouse Pearson textbook' },
  ],
  questions: ["What do you most want to understand by the end of the term?"],
};

export const SUGGESTIONS = [
  "Explain this module simply",
  "Quiz me on this",
  "Why does this matter today?",
  "Give a real-world example",
];
