// Shared helpers for locating pre-generated seminar voice narration.
//
// MP3s are generated by scripts/generate_seminar_audio.mjs and committed under
// public/audio/seminar/. The slug rule here MUST match that script so the
// filename a component asks for is the filename on disk.
//
//   theory_<slug>.mp3    where slug is the theory's seed `slug` field
//   pattern_<slug>.mp3   where slug = slugifyPattern(pattern.name)

// Keep in sync with slugifyPattern() in scripts/generate_seminar_audio.mjs.
export function slugifyPattern(name) {
  return String(name || "")
    .toLowerCase()
    .replace(/[–—]/g, "-") // en/em dash -> hyphen
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function theoryAudioUrl(theory) {
  if (!theory || !theory.slug) return null;
  return `/audio/seminar/theory_${theory.slug}.mp3`;
}

export function patternAudioUrl(pattern) {
  if (!pattern || !pattern.name) return null;
  return `/audio/seminar/pattern_${slugifyPattern(pattern.name)}.mp3`;
}

// Per-edition Weekly Briefing narration. Unlike the static theory/pattern MP3s,
// briefing audio is generated weekly by a cron (read-only FS) and stored in the
// DB, so it's streamed through an API route rather than served as a static file.
export function briefingAudioUrl(editionId) {
  if (editionId == null) return null;
  return `/api/seminar/briefing-audio?id=${editionId}`;
}
